# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QMainWindow, QProgressBar,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(900, 600))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 85, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(127, 170, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(63, 127, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 42, 127, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(0, 57, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush8 = QBrush(QColor(0, 0, 0, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 42, 127, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(76, 136, 255, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush10)
        MainWindow.setPalette(palette)
        icon = QIcon()
        icon.addFile(u"assets/ans.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.startButton = QPushButton(self.centralwidget)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(660, 20, 51, 51))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.startButton.setFont(font)
        self.pushButton2 = QPushButton(self.centralwidget)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setGeometry(QRect(650, 270, 75, 31))
        self.pushButton2.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 10, 640, 480))
        self.label.setFrameShape(QFrame.Shape.Box)
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(10, 500, 631, 71))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        self.label2.setFont(font1)
        self.label2.setFrameShape(QFrame.Shape.StyledPanel)
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(660, 200, 51, 61))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.checkBox.setFont(font2)
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.checkBox.setAutoFillBackground(False)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.AudioVolumeMedium))
        self.checkBox.setIcon(icon1)
        self.checkBox.setIconSize(QSize(32, 32))
        self.checkBox.setTristate(False)
        self.pushButton3 = QPushButton(self.centralwidget)
        self.pushButton3.setObjectName(u"pushButton3")
        self.pushButton3.setGeometry(QRect(730, 150, 151, 31))
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(730, 10, 151, 134))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)

        self.spinBox2 = QSpinBox(self.gridLayoutWidget)
        self.spinBox2.setObjectName(u"spinBox2")
        font3 = QFont()
        font3.setPointSize(10)
        self.spinBox2.setFont(font3)
        self.spinBox2.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox2.setMaximum(100)
        self.spinBox2.setValue(75)

        self.gridLayout.addWidget(self.spinBox2, 1, 1, 1, 1)

        self.label_2 = QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.spinBox1 = QSpinBox(self.gridLayoutWidget)
        self.spinBox1.setObjectName(u"spinBox1")
        self.spinBox1.setFont(font3)
        self.spinBox1.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox1.setWrapping(False)
        self.spinBox1.setMaximum(100)
        self.spinBox1.setValue(75)

        self.gridLayout.addWidget(self.spinBox1, 0, 1, 1, 1)

        self.label_4 = QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)

        self.spinBox3 = QSpinBox(self.gridLayoutWidget)
        self.spinBox3.setObjectName(u"spinBox3")
        self.spinBox3.setFont(font3)
        self.spinBox3.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox3.setMaximum(100)
        self.spinBox3.setValue(75)

        self.gridLayout.addWidget(self.spinBox3, 2, 1, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)

        self.spinBox6 = QSpinBox(self.gridLayoutWidget)
        self.spinBox6.setObjectName(u"spinBox6")
        self.spinBox6.setFont(font3)
        self.spinBox6.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox6.setMaximum(100)
        self.spinBox6.setValue(75)

        self.gridLayout.addWidget(self.spinBox6, 3, 1, 1, 1)

        self.gridLayoutWidget_2 = QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(730, 200, 151, 61))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)

        self.label_5 = QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)

        self.spinBox5 = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox5.setObjectName(u"spinBox5")
        self.spinBox5.setMinimum(1)
        self.spinBox5.setMaximum(500)
        self.spinBox5.setValue(149)

        self.gridLayout_2.addWidget(self.spinBox5, 1, 1, 1, 1)

        self.spinBox4 = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox4.setObjectName(u"spinBox4")
        self.spinBox4.setMaximum(105)
        self.spinBox4.setValue(70)

        self.gridLayout_2.addWidget(self.spinBox4, 0, 1, 1, 1)

        self.pushButton4 = QPushButton(self.centralwidget)
        self.pushButton4.setObjectName(u"pushButton4")
        self.pushButton4.setGeometry(QRect(730, 270, 151, 31))
        self.pushButton4.setStyleSheet(u"file:///C:/Users/Kamil/Downloads/Chatbee.qss")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(650, 310, 231, 181))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName(u"label_7")
        font4 = QFont()
        font4.setPointSize(128)
        font4.setBold(True)
        self.label_7.setFont(font4)
        self.label_7.setFrameShape(QFrame.Shape.NoFrame)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.label_7)

        self.progressBar = QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setValue(0)
        self.progressBar.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(Qt.Orientation.Vertical)

        self.horizontalLayout.addWidget(self.progressBar)

        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(660, 500, 151, 71))
        font5 = QFont()
        font5.setPointSize(24)
        self.label_9.setFont(font5)
        self.label_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_9.setFrameShadow(QFrame.Shadow.Plain)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(820, 500, 80, 80))
        self.label_10.setPixmap(QPixmap(u"assets/ki_LOGO_w.png"))
        self.label_10.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Sign language translator", None))
        self.startButton.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"Speak", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"No frame", None))
        self.label2.setText(QCoreApplication.translate("MainWindow", u"No info", None))
        self.checkBox.setText("")
        self.pushButton3.setText(QCoreApplication.translate("MainWindow", u"Reset NN", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Presence ", None))
#if QT_CONFIG(whatsthis)
        self.spinBox2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox2.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox2.setPrefix("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Detection", None))
#if QT_CONFIG(whatsthis)
        self.spinBox1.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox1.setSpecialValueText("")
        self.spinBox1.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox1.setPrefix("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Tracking", None))
#if QT_CONFIG(whatsthis)
        self.spinBox3.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox3.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox3.setPrefix("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Treshold", None))
#if QT_CONFIG(whatsthis)
        self.spinBox6.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox6.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox6.setPrefix("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Rate", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Volume", None))
        self.spinBox4.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.pushButton4.setText(QCoreApplication.translate("MainWindow", u"Reset TTS", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"No FPS", None))
        self.label_10.setText("")
    # retranslateUi

