# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QGroupBox, QLabel, QMainWindow, QProgressBar,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1170, 769)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(1280, 800))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 85, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(127, 170, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(63, 127, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 42, 127, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(0, 57, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush8 = QBrush(QColor(0, 0, 0, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 42, 127, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(76, 136, 255, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush10)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Verdana"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"assets/ans.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_plus = QPushButton(self.centralwidget)
        self.pushButton_plus.setObjectName(u"pushButton_plus")
        self.pushButton_plus.setGeometry(QRect(680, 630, 20, 21))
        font1 = QFont()
        font1.setFamilies([u"Verdana"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.pushButton_plus.setFont(font1)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 530, 661, 211))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 20, 241, 141))
        self.gridLayoutWidget = QWidget(self.groupBox_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 20, 221, 111))
        self.gridLayout_recognizerConfig = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_recognizerConfig.setObjectName(u"gridLayout_recognizerConfig")
        self.gridLayout_recognizerConfig.setContentsMargins(0, 0, 0, 0)
        self.label_detection = QLabel(self.gridLayoutWidget)
        self.label_detection.setObjectName(u"label_detection")

        self.gridLayout_recognizerConfig.addWidget(self.label_detection, 0, 0, 1, 1)

        self.spinBox_presence = QSpinBox(self.gridLayoutWidget)
        self.spinBox_presence.setObjectName(u"spinBox_presence")
        self.spinBox_presence.setFont(font)
        self.spinBox_presence.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_presence.setMaximum(100)
        self.spinBox_presence.setValue(65)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_presence, 1, 1, 1, 1)

        self.label_presence = QLabel(self.gridLayoutWidget)
        self.label_presence.setObjectName(u"label_presence")

        self.gridLayout_recognizerConfig.addWidget(self.label_presence, 1, 0, 1, 1)

        self.spinBox_treshold = QSpinBox(self.gridLayoutWidget)
        self.spinBox_treshold.setObjectName(u"spinBox_treshold")
        self.spinBox_treshold.setFont(font)
        self.spinBox_treshold.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_treshold.setMaximum(100)
        self.spinBox_treshold.setValue(60)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_treshold, 3, 1, 1, 1)

        self.label_treshold = QLabel(self.gridLayoutWidget)
        self.label_treshold.setObjectName(u"label_treshold")

        self.gridLayout_recognizerConfig.addWidget(self.label_treshold, 3, 0, 1, 1)

        self.spinBox_detection = QSpinBox(self.gridLayoutWidget)
        self.spinBox_detection.setObjectName(u"spinBox_detection")
        self.spinBox_detection.setFont(font)
        self.spinBox_detection.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_detection.setWrapping(False)
        self.spinBox_detection.setMaximum(100)
        self.spinBox_detection.setValue(65)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_detection, 0, 1, 1, 1)

        self.spinBox_tracking = QSpinBox(self.gridLayoutWidget)
        self.spinBox_tracking.setObjectName(u"spinBox_tracking")
        self.spinBox_tracking.setFont(font)
        self.spinBox_tracking.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_tracking.setMaximum(100)
        self.spinBox_tracking.setValue(55)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_tracking, 2, 1, 1, 1)

        self.label_tracking = QLabel(self.gridLayoutWidget)
        self.label_tracking.setObjectName(u"label_tracking")

        self.gridLayout_recognizerConfig.addWidget(self.label_tracking, 2, 0, 1, 1)

        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(259, 19, 181, 141))
        self.gridLayoutWidget_2 = QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 20, 151, 52))
        self.gridLayout_ttsConfig = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_ttsConfig.setObjectName(u"gridLayout_ttsConfig")
        self.gridLayout_ttsConfig.setContentsMargins(0, 0, 0, 0)
        self.spinBox_volume = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_volume.setObjectName(u"spinBox_volume")
        self.spinBox_volume.setMaximum(105)
        self.spinBox_volume.setValue(90)

        self.gridLayout_ttsConfig.addWidget(self.spinBox_volume, 0, 1, 1, 1)

        self.label_ttsRate = QLabel(self.gridLayoutWidget_2)
        self.label_ttsRate.setObjectName(u"label_ttsRate")

        self.gridLayout_ttsConfig.addWidget(self.label_ttsRate, 1, 0, 1, 1)

        self.spinBox_ttsRate = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_ttsRate.setObjectName(u"spinBox_ttsRate")
        self.spinBox_ttsRate.setMinimum(1)
        self.spinBox_ttsRate.setMaximum(500)
        self.spinBox_ttsRate.setValue(150)

        self.gridLayout_ttsConfig.addWidget(self.spinBox_ttsRate, 1, 1, 1, 1)

        self.label_volume = QLabel(self.gridLayoutWidget_2)
        self.label_volume.setObjectName(u"label_volume")

        self.gridLayout_ttsConfig.addWidget(self.label_volume, 0, 0, 1, 1)

        self.checkBox_speak = QCheckBox(self.groupBox_3)
        self.checkBox_speak.setObjectName(u"checkBox_speak")
        self.checkBox_speak.setGeometry(QRect(10, 80, 151, 51))
        font2 = QFont()
        font2.setFamilies([u"Verdana"])
        font2.setPointSize(10)
        font2.setBold(True)
        self.checkBox_speak.setFont(font2)
        self.checkBox_speak.setAcceptDrops(False)
        self.checkBox_speak.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.checkBox_speak.setAutoFillBackground(False)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.AudioVolumeMedium))
        self.checkBox_speak.setIcon(icon1)
        self.checkBox_speak.setIconSize(QSize(32, 32))
        self.checkBox_speak.setTristate(False)
        self.pushButton_resetRecognizer = QPushButton(self.groupBox)
        self.pushButton_resetRecognizer.setObjectName(u"pushButton_resetRecognizer")
        self.pushButton_resetRecognizer.setGeometry(QRect(10, 170, 241, 31))
        self.pushButton_resetTTS = QPushButton(self.groupBox)
        self.pushButton_resetTTS.setObjectName(u"pushButton_resetTTS")
        self.pushButton_resetTTS.setGeometry(QRect(260, 170, 181, 31))
        self.pushButton_resetTTS.setStyleSheet(u"file:///C:/Users/Kamil/Downloads/Chatbee.qss")
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(450, 20, 171, 141))
        self.gridLayoutWidget_3 = QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(10, 20, 160, 101))
        self.gridLayout = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_ttsRate_3 = QLabel(self.gridLayoutWidget_3)
        self.label_ttsRate_3.setObjectName(u"label_ttsRate_3")

        self.gridLayout.addWidget(self.label_ttsRate_3, 1, 0, 1, 1)

        self.spinBox_cameraID = QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_cameraID.setObjectName(u"spinBox_cameraID")
        self.spinBox_cameraID.setMaximum(9)

        self.gridLayout.addWidget(self.spinBox_cameraID, 0, 1, 1, 1)

        self.label_ttsRate_4 = QLabel(self.gridLayoutWidget_3)
        self.label_ttsRate_4.setObjectName(u"label_ttsRate_4")

        self.gridLayout.addWidget(self.label_ttsRate_4, 2, 0, 1, 1)

        self.label_ttsRate_2 = QLabel(self.gridLayoutWidget_3)
        self.label_ttsRate_2.setObjectName(u"label_ttsRate_2")

        self.gridLayout.addWidget(self.label_ttsRate_2, 0, 0, 1, 1)

        self.spinBox_camera_width = QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_camera_width.setObjectName(u"spinBox_camera_width")
        self.spinBox_camera_width.setMinimum(1)
        self.spinBox_camera_width.setMaximum(640)
        self.spinBox_camera_width.setValue(640)

        self.gridLayout.addWidget(self.spinBox_camera_width, 1, 1, 1, 1)

        self.spinBox_camera_height = QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_camera_height.setObjectName(u"spinBox_camera_height")
        self.spinBox_camera_height.setMinimum(1)
        self.spinBox_camera_height.setMaximum(480)
        self.spinBox_camera_height.setValue(480)

        self.gridLayout.addWidget(self.spinBox_camera_height, 2, 1, 1, 1)

        self.pushButton_resetCap = QPushButton(self.groupBox)
        self.pushButton_resetCap.setObjectName(u"pushButton_resetCap")
        self.pushButton_resetCap.setGeometry(QRect(450, 170, 171, 31))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_resetCap.sizePolicy().hasHeightForWidth())
        self.pushButton_resetCap.setSizePolicy(sizePolicy1)
        self.pushButton_resetCap.setAutoDefault(False)
        self.pushButton_resetCap.setFlat(False)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(680, 10, 481, 511))
        self.groupBox_7 = QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 20, 451, 381))
        self.label_displaySign = QLabel(self.groupBox_7)
        self.label_displaySign.setObjectName(u"label_displaySign")
        self.label_displaySign.setGeometry(QRect(20, 20, 341, 341))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_displaySign.sizePolicy().hasHeightForWidth())
        self.label_displaySign.setSizePolicy(sizePolicy2)
        self.label_displaySign.setMaximumSize(QSize(400, 400))
        font3 = QFont()
        font3.setFamilies([u"Verdana"])
        font3.setPointSize(216)
        font3.setBold(True)
        self.label_displaySign.setFont(font3)
        self.label_displaySign.setFrameShape(QFrame.Shape.Box)
        self.label_displaySign.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.progressBar_1 = QProgressBar(self.groupBox_7)
        self.progressBar_1.setObjectName(u"progressBar_1")
        self.progressBar_1.setGeometry(QRect(380, 20, 50, 341))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.progressBar_1.sizePolicy().hasHeightForWidth())
        self.progressBar_1.setSizePolicy(sizePolicy3)
        self.progressBar_1.setMaximumSize(QSize(50, 400))
        self.progressBar_1.setValue(0)
        self.progressBar_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.progressBar_1.setTextVisible(True)
        self.progressBar_1.setOrientation(Qt.Orientation.Vertical)
        self.groupBox_8 = QGroupBox(self.groupBox_5)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 410, 261, 91))
        self.label_recognitionInfo = QLabel(self.groupBox_8)
        self.label_recognitionInfo.setObjectName(u"label_recognitionInfo")
        self.label_recognitionInfo.setGeometry(QRect(10, 20, 241, 61))
        font4 = QFont()
        font4.setFamilies([u"Verdana"])
        font4.setPointSize(24)
        font4.setBold(True)
        self.label_recognitionInfo.setFont(font4)
        self.label_recognitionInfo.setFrameShape(QFrame.Shape.Box)
        self.label_recognitionInfo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_9 = QGroupBox(self.groupBox_5)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(280, 410, 181, 91))
        self.label_displayFPS = QLabel(self.groupBox_9)
        self.label_displayFPS.setObjectName(u"label_displayFPS")
        self.label_displayFPS.setGeometry(QRect(10, 20, 161, 61))
        self.label_displayFPS.setFont(font4)
        self.label_displayFPS.setFrameShape(QFrame.Shape.Box)
        self.label_displayFPS.setFrameShadow(QFrame.Shadow.Plain)
        self.label_displayFPS.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 661, 511))
        self.label_displayFrame = QLabel(self.groupBox_6)
        self.label_displayFrame.setObjectName(u"label_displayFrame")
        self.label_displayFrame.setGeometry(QRect(10, 20, 640, 480))
        self.label_displayFrame.setFrameShape(QFrame.Shape.Box)
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(680, 530, 481, 91))
        self.label = QLabel(self.groupBox_10)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 20, 221, 51))
        font5 = QFont()
        font5.setFamilies([u"Verdana"])
        font5.setPointSize(26)
        font5.setItalic(True)
        self.label.setFont(font5)
        self.label_logoKI = QLabel(self.groupBox_10)
        self.label_logoKI.setObjectName(u"label_logoKI")
        self.label_logoKI.setGeometry(QRect(400, 10, 71, 71))
        self.label_logoKI.setPixmap(QPixmap(u"assets/ki_LOGO_w.png"))
        self.label_logoKI.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(710, 620, 401, 141))
        self.label_2.setPixmap(QPixmap(u"assets/at.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton_resetCap.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Sign language translator", None))
        self.pushButton_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Recognizer", None))
        self.label_detection.setText(QCoreApplication.translate("MainWindow", u"Detection", None))
#if QT_CONFIG(whatsthis)
        self.spinBox_presence.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_presence.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_presence.setPrefix("")
        self.label_presence.setText(QCoreApplication.translate("MainWindow", u"Presence ", None))
#if QT_CONFIG(whatsthis)
        self.spinBox_treshold.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_treshold.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_treshold.setPrefix("")
        self.label_treshold.setText(QCoreApplication.translate("MainWindow", u"Treshold", None))
#if QT_CONFIG(whatsthis)
        self.spinBox_detection.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_detection.setSpecialValueText("")
        self.spinBox_detection.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_detection.setPrefix("")
#if QT_CONFIG(whatsthis)
        self.spinBox_tracking.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_tracking.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_tracking.setPrefix("")
        self.label_tracking.setText(QCoreApplication.translate("MainWindow", u"Tracking", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Speaker", None))
        self.spinBox_volume.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_ttsRate.setText(QCoreApplication.translate("MainWindow", u"Rate", None))
        self.label_volume.setText(QCoreApplication.translate("MainWindow", u"Volume", None))
        self.checkBox_speak.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.pushButton_resetRecognizer.setText(QCoreApplication.translate("MainWindow", u"Reset Recognizer", None))
        self.pushButton_resetTTS.setText(QCoreApplication.translate("MainWindow", u"Reset Speaker", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.label_ttsRate_3.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.label_ttsRate_4.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.label_ttsRate_2.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.pushButton_resetCap.setText(QCoreApplication.translate("MainWindow", u"Reset Camera", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Result", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Predicted Sign", None))
        self.label_displaySign.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Hand", None))
        self.label_recognitionInfo.setText(QCoreApplication.translate("MainWindow", u"No info", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Recognition Rate", None))
        self.label_displayFPS.setText(QCoreApplication.translate("MainWindow", u"No FPS", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Live view", None))
        self.label_displayFrame.setText(QCoreApplication.translate("MainWindow", u"No frame", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Author", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Kamil Rataj", None))
        self.label_logoKI.setText("")
        self.label_2.setText("")
    # retranslateUi

