# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QMainWindow, QProgressBar,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(900, 600))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 85, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(127, 170, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(63, 127, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 42, 127, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(0, 57, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush8 = QBrush(QColor(0, 0, 0, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 42, 127, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(76, 136, 255, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush10)
        MainWindow.setPalette(palette)
        icon = QIcon()
        icon.addFile(u"assets/ans.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_plus = QPushButton(self.centralwidget)
        self.pushButton_plus.setObjectName(u"pushButton_plus")
        self.pushButton_plus.setGeometry(QRect(660, 20, 51, 51))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_plus.setFont(font)
        self.pushButton_speak = QPushButton(self.centralwidget)
        self.pushButton_speak.setObjectName(u"pushButton_speak")
        self.pushButton_speak.setGeometry(QRect(650, 270, 75, 31))
        self.pushButton_speak.setFont(font)
        self.label_displayFrame = QLabel(self.centralwidget)
        self.label_displayFrame.setObjectName(u"label_displayFrame")
        self.label_displayFrame.setGeometry(QRect(0, 10, 640, 480))
        self.label_displayFrame.setFrameShape(QFrame.Shape.Box)
        self.label_recognitionInfo = QLabel(self.centralwidget)
        self.label_recognitionInfo.setObjectName(u"label_recognitionInfo")
        self.label_recognitionInfo.setGeometry(QRect(10, 500, 631, 71))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        self.label_recognitionInfo.setFont(font1)
        self.label_recognitionInfo.setFrameShape(QFrame.Shape.StyledPanel)
        self.checkBox_speak = QCheckBox(self.centralwidget)
        self.checkBox_speak.setObjectName(u"checkBox_speak")
        self.checkBox_speak.setGeometry(QRect(660, 200, 51, 61))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.checkBox_speak.setFont(font2)
        self.checkBox_speak.setAcceptDrops(False)
        self.checkBox_speak.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.checkBox_speak.setAutoFillBackground(False)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.AudioVolumeMedium))
        self.checkBox_speak.setIcon(icon1)
        self.checkBox_speak.setIconSize(QSize(32, 32))
        self.checkBox_speak.setTristate(False)
        self.pushButton_resetRecognizer = QPushButton(self.centralwidget)
        self.pushButton_resetRecognizer.setObjectName(u"pushButton_resetRecognizer")
        self.pushButton_resetRecognizer.setGeometry(QRect(730, 150, 151, 31))
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(730, 10, 151, 134))
        self.gridLayout_recognizerConfig = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_recognizerConfig.setObjectName(u"gridLayout_recognizerConfig")
        self.gridLayout_recognizerConfig.setContentsMargins(0, 0, 0, 0)
        self.label_presence = QLabel(self.gridLayoutWidget)
        self.label_presence.setObjectName(u"label_presence")

        self.gridLayout_recognizerConfig.addWidget(self.label_presence, 1, 0, 1, 1)

        self.spinBox_presence = QSpinBox(self.gridLayoutWidget)
        self.spinBox_presence.setObjectName(u"spinBox_presence")
        font3 = QFont()
        font3.setPointSize(10)
        self.spinBox_presence.setFont(font3)
        self.spinBox_presence.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_presence.setMaximum(100)
        self.spinBox_presence.setValue(65)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_presence, 1, 1, 1, 1)

        self.label_detection = QLabel(self.gridLayoutWidget)
        self.label_detection.setObjectName(u"label_detection")

        self.gridLayout_recognizerConfig.addWidget(self.label_detection, 0, 0, 1, 1)

        self.spinBox_detection = QSpinBox(self.gridLayoutWidget)
        self.spinBox_detection.setObjectName(u"spinBox_detection")
        self.spinBox_detection.setFont(font3)
        self.spinBox_detection.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_detection.setWrapping(False)
        self.spinBox_detection.setMaximum(100)
        self.spinBox_detection.setValue(65)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_detection, 0, 1, 1, 1)

        self.label_tracking = QLabel(self.gridLayoutWidget)
        self.label_tracking.setObjectName(u"label_tracking")

        self.gridLayout_recognizerConfig.addWidget(self.label_tracking, 2, 0, 1, 1)

        self.spinBox_tracking = QSpinBox(self.gridLayoutWidget)
        self.spinBox_tracking.setObjectName(u"spinBox_tracking")
        self.spinBox_tracking.setFont(font3)
        self.spinBox_tracking.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_tracking.setMaximum(100)
        self.spinBox_tracking.setValue(55)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_tracking, 2, 1, 1, 1)

        self.label_treshold = QLabel(self.gridLayoutWidget)
        self.label_treshold.setObjectName(u"label_treshold")

        self.gridLayout_recognizerConfig.addWidget(self.label_treshold, 3, 0, 1, 1)

        self.spinBox_treshold = QSpinBox(self.gridLayoutWidget)
        self.spinBox_treshold.setObjectName(u"spinBox_treshold")
        self.spinBox_treshold.setFont(font3)
        self.spinBox_treshold.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        self.spinBox_treshold.setMaximum(100)
        self.spinBox_treshold.setValue(60)

        self.gridLayout_recognizerConfig.addWidget(self.spinBox_treshold, 3, 1, 1, 1)

        self.gridLayoutWidget_2 = QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(730, 200, 151, 61))
        self.gridLayout_ttsConfig = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_ttsConfig.setObjectName(u"gridLayout_ttsConfig")
        self.gridLayout_ttsConfig.setContentsMargins(0, 0, 0, 0)
        self.label_ttsRate = QLabel(self.gridLayoutWidget_2)
        self.label_ttsRate.setObjectName(u"label_ttsRate")

        self.gridLayout_ttsConfig.addWidget(self.label_ttsRate, 1, 0, 1, 1)

        self.label_volume = QLabel(self.gridLayoutWidget_2)
        self.label_volume.setObjectName(u"label_volume")

        self.gridLayout_ttsConfig.addWidget(self.label_volume, 0, 0, 1, 1)

        self.spinBox_ttsRate = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_ttsRate.setObjectName(u"spinBox_ttsRate")
        self.spinBox_ttsRate.setMinimum(1)
        self.spinBox_ttsRate.setMaximum(500)
        self.spinBox_ttsRate.setValue(150)

        self.gridLayout_ttsConfig.addWidget(self.spinBox_ttsRate, 1, 1, 1, 1)

        self.spinBox_volume = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_volume.setObjectName(u"spinBox_volume")
        self.spinBox_volume.setMaximum(105)
        self.spinBox_volume.setValue(90)

        self.gridLayout_ttsConfig.addWidget(self.spinBox_volume, 0, 1, 1, 1)

        self.pushButton_resetTTS = QPushButton(self.centralwidget)
        self.pushButton_resetTTS.setObjectName(u"pushButton_resetTTS")
        self.pushButton_resetTTS.setGeometry(QRect(730, 270, 151, 31))
        self.pushButton_resetTTS.setStyleSheet(u"file:///C:/Users/Kamil/Downloads/Chatbee.qss")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(650, 310, 231, 208))
        self.horizontalLayout_displaySign = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_displaySign.setObjectName(u"horizontalLayout_displaySign")
        self.horizontalLayout_displaySign.setContentsMargins(0, 0, 0, 0)
        self.label_displaySign = QLabel(self.horizontalLayoutWidget)
        self.label_displaySign.setObjectName(u"label_displaySign")
        font4 = QFont()
        font4.setPointSize(116)
        font4.setBold(True)
        self.label_displaySign.setFont(font4)
        self.label_displaySign.setFrameShape(QFrame.Shape.NoFrame)
        self.label_displaySign.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_displaySign.addWidget(self.label_displaySign)

        self.progressBar_1 = QProgressBar(self.horizontalLayoutWidget)
        self.progressBar_1.setObjectName(u"progressBar_1")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.progressBar_1.sizePolicy().hasHeightForWidth())
        self.progressBar_1.setSizePolicy(sizePolicy1)
        self.progressBar_1.setValue(0)
        self.progressBar_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.progressBar_1.setTextVisible(True)
        self.progressBar_1.setOrientation(Qt.Orientation.Vertical)

        self.horizontalLayout_displaySign.addWidget(self.progressBar_1)

        self.label_displayFPS = QLabel(self.centralwidget)
        self.label_displayFPS.setObjectName(u"label_displayFPS")
        self.label_displayFPS.setGeometry(QRect(660, 500, 151, 71))
        font5 = QFont()
        font5.setPointSize(24)
        self.label_displayFPS.setFont(font5)
        self.label_displayFPS.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_displayFPS.setFrameShadow(QFrame.Shadow.Plain)
        self.label_logoKI = QLabel(self.centralwidget)
        self.label_logoKI.setObjectName(u"label_logoKI")
        self.label_logoKI.setGeometry(QRect(820, 500, 80, 80))
        self.label_logoKI.setPixmap(QPixmap(u"assets/ki_LOGO_w.png"))
        self.label_logoKI.setScaledContents(True)
        self.pushButton_resetCap = QPushButton(self.centralwidget)
        self.pushButton_resetCap.setObjectName(u"pushButton_resetCap")
        self.pushButton_resetCap.setGeometry(QRect(650, 150, 71, 31))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_resetCap.sizePolicy().hasHeightForWidth())
        self.pushButton_resetCap.setSizePolicy(sizePolicy2)
        self.pushButton_resetCap.setAutoDefault(False)
        self.pushButton_resetCap.setFlat(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton_resetCap.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Sign language translator", None))
        self.pushButton_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_speak.setText(QCoreApplication.translate("MainWindow", u"Speak", None))
        self.label_displayFrame.setText(QCoreApplication.translate("MainWindow", u"No frame", None))
        self.label_recognitionInfo.setText(QCoreApplication.translate("MainWindow", u"No info", None))
        self.checkBox_speak.setText("")
        self.pushButton_resetRecognizer.setText(QCoreApplication.translate("MainWindow", u"Reset Recognizer", None))
        self.label_presence.setText(QCoreApplication.translate("MainWindow", u"Presence ", None))
#if QT_CONFIG(whatsthis)
        self.spinBox_presence.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_presence.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_presence.setPrefix("")
        self.label_detection.setText(QCoreApplication.translate("MainWindow", u"Detection", None))
#if QT_CONFIG(whatsthis)
        self.spinBox_detection.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_detection.setSpecialValueText("")
        self.spinBox_detection.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_detection.setPrefix("")
        self.label_tracking.setText(QCoreApplication.translate("MainWindow", u"Tracking", None))
#if QT_CONFIG(whatsthis)
        self.spinBox_tracking.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_tracking.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_tracking.setPrefix("")
        self.label_treshold.setText(QCoreApplication.translate("MainWindow", u"Treshold", None))
#if QT_CONFIG(whatsthis)
        self.spinBox_treshold.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.spinBox_treshold.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.spinBox_treshold.setPrefix("")
        self.label_ttsRate.setText(QCoreApplication.translate("MainWindow", u"Rate", None))
        self.label_volume.setText(QCoreApplication.translate("MainWindow", u"Volume", None))
        self.spinBox_volume.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.pushButton_resetTTS.setText(QCoreApplication.translate("MainWindow", u"Reset TTS", None))
        self.label_displaySign.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_displayFPS.setText(QCoreApplication.translate("MainWindow", u"No FPS", None))
        self.label_logoKI.setText("")
        self.pushButton_resetCap.setText(QCoreApplication.translate("MainWindow", u"Reset Cap", None))
    # retranslateUi

